(function(){
'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);
function d(a,b){if(b)a:{var c=ca;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];if(!(f in c))break a;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
d("Array.from",function(a){return a?a:function(b,c,e){c=null!=c?c:function(l){return l};var f=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var k=0;!(g=b.next()).done;)f.push(c.call(e,g.value,k++))}else for(g=b.length,k=0;k<g;k++)f.push(c.call(e,b[k],k));return f}});function da(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
d("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(f||"")+"_"+e++,f)}function c(f,g){this.l=f;aa(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.l};var e=0;return b});
d("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var e=ca[b[c]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&aa(e.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(da(this))}})}return a});function ea(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function fa(a,b){a instanceof String&&(a+="");var c=0,e=!1,f={next:function(){if(!e&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}e=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f}d("Array.prototype.keys",function(a){return a?a:function(){return fa(this,function(b){return b})}});
d("Array.prototype.fill",function(a){return a?a:function(b,c,e){var f=this.length||0;0>c&&(c=Math.max(0,f+c));if(null==e||e>f)e=f;e=Number(e);0>e&&(e=Math.max(0,f+e));for(c=Number(c||0);c<e;c++)this[c]=b;return this}});function h(a){return a?a:Array.prototype.fill}d("Int8Array.prototype.fill",h);d("Uint8Array.prototype.fill",h);d("Uint8ClampedArray.prototype.fill",h);d("Int16Array.prototype.fill",h);d("Uint16Array.prototype.fill",h);d("Int32Array.prototype.fill",h);
d("Uint32Array.prototype.fill",h);d("Float32Array.prototype.fill",h);d("Float64Array.prototype.fill",h);
var ha={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",addpoints:"vec2 addpoints(vec3 a,vec3 b){\nreturn dehomogenize(a) +dehomogenize(b);\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arccosf:"vec2 arccosf(float z){\nif(abs(z)<=1.)return vec2(acos(z),0.);\nelse if(z>1.)return vec2(0,log(z+sqrt(z*z-1.)));\nelse return vec2(pi, -log(-z+sqrt(z*z-1.)));\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",
arcsinf:"vec2 arcsinf(float z){\nif(abs(z)<=1.)return vec2(asin(z),0.);\nelse if(z>1.)return vec2(pi*.5, -log(z+sqrt(z*z-1.)));\nelse return vec2(-pi*.5,log(-z+sqrt(z*z-1.)));\n}\n",arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",arctan2cvec2:"vec2 arctan2cvec2(cvec2 v){\nreturn arctan2c(v.real,v.imag);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",
blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",
cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",dehomogenizex:"float dehomogenizex(vec3 z){\nreturn z.x/z.z;\n}\n",dehomogenizey:"float dehomogenizey(vec3 z){\nreturn z.y/z.z;\n}\n",
det2:"float det2(mat2 a){\nreturn a[0][0]*a[1][1] -a[0][1]*a[1][0];\n}\n",det3:"float det3(mat3 a){\nreturn dot(cross(a[0],a[1]),a[2]);\n}\n",det3v:"float det3v(vec3 a,vec3 b,vec3 c){\nreturn dot(cross(a,b),c);\n}\n",det4:"float det4(mat4 a){\nfloat s00=a[0][0]*a[1][1] -a[0][1]*a[1][0],\ns01=a[0][0]*a[1][2] -a[0][2]*a[1][0],\ns02=a[0][0]*a[1][3] -a[0][3]*a[1][0],\ns03=a[0][1]*a[1][2] -a[0][2]*a[1][1],\ns04=a[0][1]*a[1][3] -a[0][3]*a[1][1],\ns05=a[0][2]*a[1][3] -a[0][3]*a[1][2],\ns06=a[2][0]*a[3][1] -a[2][1]*a[3][0],\ns07=a[2][0]*a[3][2] -a[2][2]*a[3][0],\ns08=a[2][0]*a[3][3] -a[2][3]*a[3][0],\ns09=a[2][1]*a[3][2] -a[2][2]*a[3][1],\ns10=a[2][1]*a[3][3] -a[2][3]*a[3][1],\ns11=a[2][2]*a[3][3] -a[2][3]*a[3][2];\nreturn s00*s11-s01*s10+s02*s09+s03*s08-s04*s07+s05*s06;\n}\n",
divc:"vec2 divc(vec2 a,vec2 b){\nreturn vec2(dot(a,b),dot(a,vec2(-b.y,b.x)))/dot(b,b);\n}\n",divfc:"vec2 divfc(float a,vec2 b){\nreturn a*vec2(b.x,-b.y)/dot(b,b);\n}\n",expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",
hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",
mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(dot(a,vec2(b.x,-b.y)),dot(a,b.yx));\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn(b.x==0. &&b.y==0.) ?vec2(1.,0.) : ((a.x==0. &&a.y==0.) ?vec2(0.) :expc(multc(logc(a),b)));\n}\n",powi:"float powi(float a,int b){\nif(mod(float(b),2.) < .5)\nreturn pow(abs(a),float(b));\nelse\nreturn sign(a)*pow(abs(a),float(b));\n}\n",
random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=fract(132422.21*sin(dot(plain_pixel,343433.671228*vec2(.176574+last_rnd, .1131+rnd_))));\nfloat b=fract(last_rnd*2321.2312*sin(dot(plain_pixel+vec2(rnd_,last_rnd),plain_pixel) *43758.5453));\nlast_rnd=fract(rnd_ +last_rnd+a+b);\nreturn last_rnd;\n}\n",randomnormal:"float randomnormal(){\nreturn sqrt(-2. *log(random())) *cos(6.283185307179586*random());\n}\n",realc:"float realc(vec2 a){\nreturn a.x;\n}\n",red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",
rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\nprecision highp int;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",subpoints:"vec2 subpoints(vec3 a,vec3 b){\nreturn dehomogenize(a) -dehomogenize(b);\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",
vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ia=!1,p,r,ja,ka,v,w,x=!1,la,y=!1,ma=!1,na=1;
function oa(){function a(e){p.removeEventListener("webglcontextcreationerror",a,!1);e.statusMessage&&(b=e.statusMessage)}if(!ia){p=document.createElement("canvas");p.id="glcanvas";p.style.display="none";p.width=p.height=0;document.body.appendChild(p);r=document.createElement("canvas");r.id="tmpcanvas";r.style.display="none";r.width=r.height=0;document.body.appendChild(r);ja=document.createElement("canvas");ja.id="dummycanvas";ja.style.display="none";ja.width=ja.height=1;document.body.appendChild(ja);
ka={ctype:"image",value:{img:ja,width:1,height:1,ready:!0,live:!1,generation:0,whenReady:function(){}}};var b="Unknown";p.addEventListener("webglcontextcreationerror",a,!1);var c={};"undefined"!==typeof CindyJS._pluginRegistry.CindyXR&&(c.xrCompatible=!0);(v=p.getContext("webgl",c))||(v=p.getContext("experimental-webgl",c));if(!v)throw new pa("Could not obtain a WebGL context.\nReason: "+b);qa.gl=v;p.removeEventListener("webglcontextcreationerror",a,!1);ma||(y=v.getExtension("OES_texture_float")&&
v.getExtension("OES_texture_float_linear"),y||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(x=(la=v.getExtension("OES_texture_half_float"))&&v.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures.")),navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are using an iPhone/iPad."),y=x=!1,v.getExtension("OES_texture_half_float")&&v.getExtension("OES_texture_half_float_linear")&&
v.getExtension("EXT_color_buffer_half_float")?x=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures.")));ia=!0}};function ra(a){if(null==a||"object"!=typeof a)return a;if(a instanceof Array){var b=[];for(var c=0,e=a.length;c<e;c++)b[c]=ra(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=ra(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function ua(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,e=a.length;c<e;c++)if(!ua(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(e=0;e<c.length;e++){var f=c[e];if(!ua(a[f],b[f]))return!1}return!0}return!1}function va(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function wa(a){if("boolean"===a.ctype)return z.C;if("number"===a.ctype)return a=a.value,1E-5>Math.abs(a.imag)?(a.real|0)===a.real?z.v:z.h:z.i;if("list"===a.ctype){var b=a.value;if(3===b.length){if("Point"===a.usage)return z.B;if("Line"===a.usage)return z.line}if(0<b.length){for(var c=wa(b[0]),e=1;e<b.length;e++)c=A(c,wa(b[e]));if(c)return{type:"list",length:b.length,parameters:c}}}else{if("string"===a.ctype||"image"===a.ctype)return z.image;if("geo"===a.ctype&&"L"===a.value.kind)return z.line}console.error("Cannot guess type of the following type:");
console.log(a);return!1}var xa=0;function ya(){xa++;return"_h"+xa}function za(a,b){if(a>p.width||b>p.height)p.width=Math.ceil(a),p.height=Math.ceil(b)}function Aa(a,b){a.instance.ja||(a.instance.ja={});a.instance.ja[b]||(a.instance.ja[b]=a.instance.parse(b));a=a.evaluate(a.instance.ja[b]);return a.ctype&&"number"===a.ctype?a.value.real:0}function Ba(a){return{x:Aa(a,"(screenbounds()_4).x"),y:Aa(a,"(screenbounds()_4).y")}}
function Ca(a){return{x:Aa(a,"(screenbounds()_3).x"),y:Aa(a,"(screenbounds()_3).y")}}var Da=new Float32Array(1),Ea=new Int32Array(Da.buffer);function Fa(a){Da[0]=a;a=Ea[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Ga(a){return y?new Float32Array(a):x?new Uint16Array(a):new Uint8Array(a)}function Ha(){return y?v.FLOAT:x?la.HALF_FLOAT_OES:v.UNSIGNED_BYTE}function Ia(a){for(var b=1;b<a;)b<<=1;return b};function Ja(a,b,c){if(a.canvaswrapper){if(!a.ready||a.canvaswrapper.canvas!=ka&&a.canvaswrapper.N==a.width&&a.canvaswrapper.I==a.height||(delete a.canvaswrapper,a.canvaswrapper=Ja(a,b,c)),c){b=a.canvaswrapper;var e=b.l;if(c&&(c.repeat!=e.repeat||c.clamptoedge!=e.clamptoedge||c.mipmap!=e.mipmap||c.interpolate!=e.interpolate))for(b.l=c,e=0;2>e;e++)v.bindTexture(v.TEXTURE_2D,b.textures[e]),c.mipmap?v.texParameteri(v.TEXTURE_2D,v.TEXTURE_MIN_FILTER,c.interpolate?v.LINEAR_MIPMAP_LINEAR:v.NEAREST_MIPMAP_LINEAR):
v.texParameteri(v.TEXTURE_2D,v.TEXTURE_MIN_FILTER,c.interpolate?v.LINEAR:v.NEAREST),v.texParameteri(v.TEXTURE_2D,v.TEXTURE_MAG_FILTER,c.interpolate?v.LINEAR:v.NEAREST),c.clamptoedge&&(v.texParameteri(v.TEXTURE_2D,v.TEXTURE_WRAP_S,v.CLAMP_TO_EDGE),v.texParameteri(v.TEXTURE_2D,v.TEXTURE_WRAP_T,v.CLAMP_TO_EDGE))}}else a.canvaswrapper=new Ka(a.ready?a:ka,c||{interpolate:!0,mipmap:!1,repeat:!1,clamptoedge:!1}),a.ready||console.log("Image is not ready yet.");return a.canvaswrapper}
function Ka(a,b){this.canvas=a;this.l=b;this.N=a.width;this.I=a.height;La(this);this.it=0;this.textures=[];this.$=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.readPixels=this.na.bind(this);a.cdyUpdate=this.ra.bind(this);a=Ga(this.S*this.O*4);for(var c=0;2>c;c++)this.textures[c]=v.createTexture(),v.bindTexture(v.TEXTURE_2D,this.textures[c]),v.pixelStorei(v.UNPACK_ALIGNMENT,1),v.texImage2D(v.TEXTURE_2D,0,v.RGBA,this.S,this.O,0,v.RGBA,Ha(),a),b.mipmap?v.texParameteri(v.TEXTURE_2D,
v.TEXTURE_MIN_FILTER,b.interpolate?v.LINEAR_MIPMAP_LINEAR:v.NEAREST_MIPMAP_LINEAR):v.texParameteri(v.TEXTURE_2D,v.TEXTURE_MIN_FILTER,b.interpolate?v.LINEAR:v.NEAREST),v.texParameteri(v.TEXTURE_2D,v.TEXTURE_MAG_FILTER,b.interpolate?v.LINEAR:v.NEAREST),b.clamptoedge&&(v.texParameteri(v.TEXTURE_2D,v.TEXTURE_WRAP_S,v.CLAMP_TO_EDGE),v.texParameteri(v.TEXTURE_2D,v.TEXTURE_WRAP_T,v.CLAMP_TO_EDGE)),this.$[c]=v.createFramebuffer(),v.bindFramebuffer(v.FRAMEBUFFER,this.$[c]),v.framebufferTexture2D(v.FRAMEBUFFER,
v.COLOR_ATTACHMENT0,v.TEXTURE_2D,this.textures[c],0);this.D=new Ma(ha.copytexture_v,ha.copytexture_f);b=v.createBuffer();v.bindBuffer(v.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]);a=v.getAttribLocation(this.D.handle,"aPos");v.enableVertexAttribArray(a);c=v.getAttribLocation(this.D.handle,"aTexCoord");v.enableVertexAttribArray(c);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;v.bufferData(v.ARRAY_BUFFER,f+e.byteLength,v.STATIC_DRAW);v.bufferSubData(v.ARRAY_BUFFER,0,
b);v.bufferSubData(v.ARRAY_BUFFER,f,e);v.vertexAttribPointer(a,3,v.FLOAT,!1,0,0);v.vertexAttribPointer(c,2,v.FLOAT,!1,0,f)}function La(a){a.l.clamptoedge&&a.l.interpolate&&!a.l.repeat&&!a.l.mipmap?(a.S=a.N,a.O=a.I):(a.S=Ia(a.N+a.N/2*(a.l.mipmap&&a.l.repeat)),a.O=Ia(a.I+a.I/2*(a.l.mipmap&&a.l.repeat)))}Ka.prototype.bindTexture=function(){v.bindTexture(v.TEXTURE_2D,this.textures[this.it])};Ka.prototype.bindFramebuffer=function(){v.bindFramebuffer(v.FRAMEBUFFER,this.$[this.it^1]);this.it^=1};
Ka.prototype.ra=function(){if(this.canvas.img.hasOwnProperty("getContext"))var a=this.canvas.img.getContext("2d");else this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.N,this.canvas.img.height=this.I,a=this.canvas.img.getContext("2d");a.clearRect(0,0,this.N,this.I);this.drawTo(a,0,0);this.canvas.img.generation++};
Ka.prototype.reloadIfRequired=function(){if(!(this.canvas.live&&(this.canvas.img.webkitDecodedFrameCount||this.canvas.img.l)&&this.ha>=(this.canvas.img.webkitDecodedFrameCount||this.canvas.img.l)||!this.canvas.live&&(!this.canvas.ready||this.generation>=this.canvas.generation))){if(this.N!=this.canvas.width||this.I!=this.canvas.height){this.N=this.canvas.width;this.I=this.canvas.height;La(this);for(var a=Ga(this.S*this.O*4),b=0;2>b;b++)v.bindTexture(v.TEXTURE_2D,this.textures[b]),v.texImage2D(v.TEXTURE_2D,
0,v.RGBA,this.S,this.O,0,v.RGBA,Ha(),a)}this.bindTexture();v.pixelStorei(v.UNPACK_FLIP_Y_WEBGL,1);this.l.repeat?(r.width=this.S,r.height=this.O,a=r.getContext("2d"),a.drawImage(this.canvas.img,0,this.O-this.I),a.drawImage(this.canvas.img,this.N,this.O-this.I),a.drawImage(this.canvas.img,0,this.O-2*this.I),a.drawImage(this.canvas.img,this.N,this.O-2*this.I),v.texSubImage2D(v.TEXTURE_2D,0,0,0,v.RGBA,Ha(),r)):v.texSubImage2D(v.TEXTURE_2D,0,0,0,v.RGBA,Ha(),this.canvas.img);this.l.mipmap&&v.generateMipmap(v.TEXTURE_2D);
v.pixelStorei(v.UNPACK_FLIP_Y_WEBGL,0);this.generation=this.canvas.generation;this.ha=Math.min(this.ha+1,this.canvas.img.webkitDecodedFrameCount||this.canvas.img.l)}};
Ka.prototype.drawTo=function(a,b,c){za(this.S,this.O);v.viewport(0,0,this.S,this.O);this.D.use(v);v.activeTexture(v.TEXTURE0);v.bindTexture(v.TEXTURE_2D,this.textures[this.it]);this.D.uniform.sampler([0]);v.bindFramebuffer(v.FRAMEBUFFER,null);v.drawArrays(v.TRIANGLE_STRIP,0,4);v.flush();a.drawImage(p,0,p.height-this.I,this.N,this.I,b,c,this.N,this.I)};
Ka.prototype.na=function(a,b,c,e){v.bindFramebuffer(v.FRAMEBUFFER,this.$[this.it]);v.framebufferTexture2D(v.FRAMEBUFFER,v.COLOR_ATTACHMENT0,v.TEXTURE_2D,this.textures[this.it],0);var f=Ga(c*e*4);v.readPixels(a,this.I-b-e,c,e,v.RGBA,Ha(),f);a=[];for(--e;0<=e;e--){b=a.concat;for(var g=f.slice(e*c*4,(e+1)*c*4),k=[],l=0;l<g.length;l++)if(y)k.push(g[l]);else if(x){var m=g[l],q=(m&31744)>>10,n=m&1023;k.push((m>>15?-1:1)*(q?31===q?n?NaN:Infinity:Math.pow(2,q-15)*(1+n/1024):n/1024*6.103515625E-5))}else k.push(g[l]/
255);a=b.call(a,k)}return a};function Na(a,b){this.F=a;this.$=b;Oa(this)}
function Oa(a){var b=Pa(new Qa(a.F),a.$);a.D=b.G;a.P=b.P;a.ga=b.ga;a.ha=ha.standardFragmentHeader+b.code;a.na=ha.vshader;a.l=new Ma(a.na,a.ha);b=v.createBuffer();v.bindBuffer(v.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]);var c=v.getAttribLocation(a.l.handle,"aPos");v.enableVertexAttribArray(c);a=v.getAttribLocation(a.l.handle,"aTexCoord");v.enableVertexAttribArray(a);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;v.bufferData(v.ARRAY_BUFFER,f+e.byteLength,v.STATIC_DRAW);
v.bufferSubData(v.ARRAY_BUFFER,0,b);v.bufferSubData(v.ARRAY_BUFFER,f,e);v.vertexAttribPointer(c,3,v.FLOAT,!1,0,0);v.vertexAttribPointer(a,2,v.FLOAT,!1,0,f)}function Ra(a,b,c,e){b=[c.x-b.x,e.x-b.x,b.x,c.y-b.y,e.y-b.y,b.y,0,0,1];a.l.uniform.hasOwnProperty("transformMatrix")&&a.l.uniform.transformMatrix([b[0],b[3],b[6],b[1],b[4],b[7],b[2],b[5],b[8]])}
function Sa(a){function b(g,k,l){if(g)if("function"===typeof g)switch(k){case z.i:g([l.value.real,l.value.imag]);break;case z.C:l.value?g([1]):g([0]);break;case z.v:case z.h:g([l.value.real]);break;case z.B:case z.line:"geo"===l.ctype?g(l.value.homog.value.map(function(u){return u.value.real})):"list"===l.ctype&&2===l.value.length?g(l.value.map(function(u){return u.value.real}).concat([1])):"list"===l.ctype&&3===l.value.length&&g(l.value.map(function(u){return u.value.real}));break;default:if("list"===
k.type&&k.parameters===z.h)g(l.value.map(function(u){return u.value.real}));else if("list"===k.type&&"list"===k.parameters.type&&k.parameters.parameters===z.h){for(var m=[],q=0;q<k.length;q++)for(var n=0;n<k.parameters.length;n++)m.push(l.value[q].value[n].value.real);g(m)}else console.error("Don't know how to set uniform of type "+B(k)+", to "+l)}else if("list"===k.type)if(q=Ta(k),1===C(k)&&q===z.h){k=Ua(k.length);var t=0;for(m in k)b(g["a"+m],z.da(k[m]),{ctype:"list",value:E(k[m]).map(function(u){return l.value[t+
u]})}),t+=k[m]}else for(m=0;m<k.length;m++)b(g["a"+m],k.parameters,{ctype:"list",value:l.value[m].value});else console.error("Don't know how to set uniform of type "+B(k)+", to"),console.log(l)}for(var c in a.D){var e=a.F.evaluateAndVal(a.D[c].W),f=a.D[c].type;if(!F(Va(e),f)){console.log("Type of "+c+" changed ("+B(Va(e))+" is no subtype of  "+B(f)+"); forcing rebuild.");Oa(a);a.l.use(v);Sa(a);return}a.l.uniform[c]&&b(a.l.uniform[c],f,e)}[["rnd_",function(){return[Math.random()]}],["_lowerleft",function(){var g=
Ba(a.F);return[g.x,g.y]}],["_lowerright",function(){var g=Ca(a.F);return[g.x,g.y]}]].map(function(g){return a.l.uniform[g[0]]&&a.l.uniform[g[0]](g[1]())})}function Wa(a){var b=0,c;for(c in a.P){v.activeTexture(v.TEXTURE0+b);var e=a.P[c],f=e.name;e=Xa(e);e.reloadIfRequired();e.bindTexture();[["_sampler"+f,[b]],["_ratio"+f,[e.N/e.I]],["_cropfact"+f,[e.N/e.S,e.I/e.O]]].map(function(g){return a.l.uniform[g[0]]&&a.l.uniform[g[0]](g[1])});b++}}
function Ya(a){for(var b in a.ga)if(a.F.getMyfunction(b).generation>a.ga[b])return console.log(b+" is outdated; forcing rebuild."),!1;return!0};function qa(a){function b(c,e,f,g,k,l){if(!c.ma||c.la<na)c.ma=!0,c.la=na,c.oa=new Na(a,c);c=c.oa;Ya(c)||Oa(c);var m=k/g;m={x:e.x+-(f.y-e.y)*m,y:e.y+(f.x-e.x)*m};za(g,k);l?v.viewport(0,0,g,k):v.viewport(0,p.height-k,g,k);c.l.use(v);Sa(c);Ra(c,e,f,m);Wa(c);l?(l.bindFramebuffer(),l.generation=++l.canvas.generation):v.bindFramebuffer(v.FRAMEBUFFER,null);v.drawArrays(v.TRIANGLE_STRIP,0,4);v.flush();l&&(l.generation=Math.max(l.generation,l.canvas.generation+1))}w=a.nada;a.defineFunction("compile",1,function(c){c=
Pa(new Qa(a),c[0]);console.log(c);return{ctype:"string",value:c}});a.defineFunction("use8bittextures",0,function(){ma=!0;y=x=!1;console.log("Switching to 8-bit textures mode.");return a.nada});a.defineFunction("forcerecompile",0,function(){na++;return w});a.defineFunction("colorplot",1,function(c){oa();var e=a.instance.canvas.width,f=a.instance.canvas.height;b(c[0],Ba(a),Ca(a),e,f,null);c=a.instance.canvas.getContext("2d");c.save();c.setTransform(1,0,0,1,0,0);c.drawImage(p,0,0,e,f,0,0,e,f);c.restore();
return w});a.defineFunction("colorplot",3,function(c){oa();var e=c[0],f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.extractPoint(a.evaluateAndVal(c[2])),k={x:Math.min(f.x,g.x),y:Math.min(f.y,g.y)},l={x:Math.max(f.x,g.x),y:Math.min(f.y,g.y)},m=Math.min(f.x,g.x),q=Math.max(f.y,g.y);c=a.instance.canvas.width;var n=a.instance.canvas.height;var t=Aa(a,"(screenbounds()_1).x");var u=Aa(a,"(screenbounds()_1).y");var D=Ca(a),K=Math.abs((f.x-g.x)/(D.x-t));f=Math.abs((f.y-g.y)/(D.y-u));b(e,k,l,c*K,n*f,null);
e=a.instance.canvas.getContext("2d");a.getInitialMatrix();t=c*(m-t)/(D.x-t);u=n*(q-u)/(D.y-u);e.save();e.setTransform(1,0,0,1,0,0);e.drawImage(p,0,0,c*K,n*f,t,u,c*K,n*f);e.restore();return w});a.defineFunction("colorplot",4,function(c){oa();var e=a.extractPoint(a.evaluateAndVal(c[0])),f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.evaluateAndVal(c[2]);c=c[3];if(!e.ok||!f.ok||"string"!==g.ctype)return w;g=a.getImage(g.value,!0);var k=Ja(g,a,!1);b(c,e,f,g.width,g.height,k);return w});a.defineFunction("colorplot",
2,function(c){oa();var e=Ba(a),f=Ca(a),g=a.evaluateAndVal(c[0]);c=c[1];if("string"!==g.ctype)return w;g=a.getImage(g.value,!0);var k=Ja(g,a,!1);b(c,e,f,g.width,g.height,k);return w});a.defineFunction("setpixel",4,function(c){var e=a.evaluateAndVal(c[0]);var f=void 0===f?null:f;if("string"===e.ctype)var g=e.value;else console.log("argument is not a string"),g=f;e=Za(a.evaluateAndVal(c[1]));f=Za(a.evaluateAndVal(c[2]));var k=$a(a.evaluateAndVal(c[3]));if(!g)return w;c=a.getImage(g,!0);c=Ja(c,a,!1);
if(isFinite(e)&&isFinite(f)&&g&&c&&k){c.bindTexture();g=[k[0],k[1],k[2],1];k=v;var l=k.texSubImage2D,m=v.TEXTURE_2D,q=v.RGBA,n=Ha();if(y)var t=new Float32Array(g);else if(x){t=new Uint16Array(g.length);for(var u=0;u<g.length;u++)t[u]=Fa(g[u])}else for(t=new Uint8Array(g.length),u=0;u<g.length;u++)t[u]=255*g[u];l.call(k,m,0,e,f,1,1,q,n,t);c=c.canvas.img.getContext("2d");k=c.createImageData(1,1);k.data.d=g;c.putImageData(k,e,f)}return w});a.defineFunction("colorplotxr",2,function(c){oa();var e=a.evaluate(c[0]).value.real;
c=c[1];if(!c.ma||c.la<na)c.ma=!0,c.la=na,c.oa=new Na(a,c);c=c.oa;if(0==e){v.clearColor(0,0,0,1);v.clear(v.COLOR_BUFFER_BIT|v.DEPTH_BUFFER_BIT);var f=v.getAttribLocation(c.l.handle,"aPos");v.enableVertexAttribArray(f);var g=v.getAttribLocation(c.l.handle,"aTexCoord");v.enableVertexAttribArray(g);v.vertexAttribPointer(f,3,v.FLOAT,!1,0,0);v.vertexAttribPointer(g,2,v.FLOAT,!1,0,48)}Ya(c)||Oa(c);c.l.use(v);Sa(c);Ra(c,{x:-1,y:-1},{x:1,y:-1},{x:-1,y:1});Wa(c);CindyJS._pluginRegistry.CindyXR.xrUpdateCindyGLView(v,
e);v.drawArrays(v.TRIANGLE_STRIP,0,4);v.flush();return w})}qa.gl=null;qa.generateCanvasWrapperIfRequired=Ja;qa.initGLIfRequired=oa;CindyJS.registerPlugin(1,"CindyGL",qa);function G(a,b){return{type:"list",length:a,parameters:b}}function Va(a){return{type:"constant",value:a}}function ab(a){return Va({ctype:"number",value:{real:a,imag:0}})}var z={C:1,v:2,h:3,i:4,V:5,color:6,B:7,line:8,M:9,image:10,H:G(2,3),L:G(3,3),R:G(4,3),da:function(a){return G(a,3)},fa:function(a){return G(a,4)},aa:G(2,G(2,3)),ba:G(3,G(3,3)),ca:G(4,G(4,3))};Object.freeze(z);
function B(a){return 1<=a&&10>=a?"bool int float complex voidt color point line coordinate2d image".split(" ")[a-1]:"list"===a.type?B(a.parameters)+"["+a.length+"]":"constant"===a.type?"const["+JSON.stringify(a.value.value)+"]":JSON.stringify(a)}function H(a){return"list"===a.type&&H(a.parameters)||F(a,z.h)}function I(a){return"list"===a.type&&I(a.parameters)||F(a,z.i)}function bb(a){return"constant"===a.type&&F(a,z.v)}function J(a){return"constant"===a.type?wa(a.value):a}
function C(a){return"list"===a.type?C(a.parameters)+1:0}function Ta(a){return void 0!==a.parameters?Ta(a.parameters):a}function cb(a,b){return C(a)===C(b)&&(0===C(a)||a.length===b.length&&cb(a.parameters,b.parameters))}function L(a){return F(a,z.h)?z.h:F(a,z.i)?z.i:{type:"list",length:a.length,parameters:L(a.parameters)}}function db(a){return F(a,z.i)?z.i:{type:"list",length:a.length,parameters:db(a.parameters)}}
function M(a){return"constant"===a.type&&M(J(a))||a===z.C||a===z.v||a===z.h||a===z.i||a===z.B||a===z.line||"list"===a.type&&a.parameters===z.h&&1<=a.length&&4>=a.length||"list"===a.type&&"list"===a.parameters.type&&a.parameters.parameters===z.h&&a.length===a.parameters.length&&2<=a.length&&4>=a.length}function eb(a){return-1!==[z.C,z.v,z.h,z.i].indexOf(a)}
function fb(a,b){return a===b||"constant"===a.type&&"constant"===b.type&&ua(a.value,b.value)||"list"===a.type&&"list"===b.type&&a.length===b.length&&fb(a.parameters,b.parameters)}
function F(a,b){return fb(a,b)?!0:a?eb(a)&&eb(b)?a<=b:"constant"===b.type?!1:"constant"===a.type?F(wa(a.value),b):b===z.M?F(a,z.i)||F(a,z.H)||F(a,z.B):b===z.B?F(a,z.L)||F(a,z.H):b===z.line?F(a,z.L):b===z.color?F(a,z.h)||"list"===a.type&&(3===a.length||4===a.length)&&F(a.parameters,z.h):"list"===a.type&&"list"===b.type&&a.length===b.length?F(a.parameters,b.parameters):!1:!1}
function A(a,b){if(!a)return b;if(!b||fb(a,b))return a;"constant"===a.type&&(a=wa(a.value));"constant"===b.type&&(b=wa(b.value));return eb(a)&&eb(b)?Math.max(a,b):"list"===a.type&&"list"===b.type&&a.length===b.length&&(b=A(a.parameters,b.parameters))?{type:"list",length:a.length,parameters:b}:!1}
function N(a){return function(b){var c={},e;for(e in a){var f=a[e];c.ea=f[0];if(b.length==c.ea.length&&b.every(function(g){return function(k,l){return F(k,g.ea[l])}}(c)))return{s:c.ea,u:f[1],m:f[2]};c={ea:c.ea}}return!1}}
function gb(a){switch(a){case z.v:return N([[[z.C],z.v,O("int")]]);case z.h:return N([[[z.C],z.h,O("float")],[[z.v],z.h,O("float")]]);case z.i:return N([[[z.h],z.i,function(b){return"vec2("+b+", 0.)"}]]);case z.color:return N([[[z.h],z.color,P("float2color")],[[z.L],z.color,function(b){return"vec4("+b+",1.0)"}],[[z.R],z.color,Q]]);case z.B:return N([[[z.H],z.B,function(b){return"vec3("+b+",1.0)"}],[[z.L],z.B,Q]]);case z.line:return N([[[z.H],z.line,function(b){return"vec3("+b+",1.0)"}],[[z.L],z.line,
Q]]);case z.M:return N([[[z.i],z.M,Q],[[z.H],z.M,Q],[[z.B],z.M,P("dehomogenize")]]);default:if("list"===a.type)return function(b){var c=b[0],e=gb(a.parameters)([c.parameters]).m;return{s:b,u:a,m:function(f,g,k){return hb(a)(E(a.length).map(function(l){return e([R(c,l)([f],g,k)],g,k)}),g,k)}}}}console.log("no inclusionfunction ->"+B(a)+" implemented yet; using identity...");return function(b){return{s:b,u:a,m:Q}}}
function S(a){a=J(a);switch(a){case z.C:return"bool";case z.v:return"int";case z.h:return"float";case z.i:case z.M:return"vec2";case z.V:return"void";case z.color:return"vec4";case z.B:case z.line:return"vec3"}if("list"===a.type&&a.parameters===z.h)return 1==a.length?"float":"vec"+a.length;if("list"===a.type&&a.parameters===z.i)return"cvec"+a.length;if("list"===a.type&&"list"===a.parameters.type&&a.length===a.parameters.length&&a.parameters.parameters===z.h)switch(a.length){case 2:return"mat2";case 3:return"mat3";
case 4:return"mat4"}if("list"===a.type)return"l"+a.length+"_"+S(a.parameters);console.error("No WebGL implementation for type "+B(a)+" found")}function ib(a,b){switch(b){case z.C:return S(b)+"("+a.value+")";case z.v:return""+(a.value.real|0);case z.h:return S(b)+"("+a.value.real+")";case z.i:return S(b)+"("+a.value.real+", "+a.value.imag+")";case z.color:return a=a.value.real,"vec4("+a+","+a+","+a+",1.)";default:console.error("Dont know how to paste values of Type "+B(b)+" yet.")}};var T={};function jb(a,b,c){if(!c.mark("includedfunctions",a)){for(var e in T[a])jb(T[a][e],b,c);c.add("includedfunctions",a,function(){return ha[a]})}}function P(a){return function(b,c,e){jb(a,c,e);return O(a)(b)}};function E(a){return Array.from(Array(a).keys())}function Ua(a){return 4>=a?[a]:5==a?[2,3]:Ua(a-4).concat([4])}function kb(a){var b=Ta(a),c=C(a);return 1==c&&b===z.h?Ua(a.length).map(function(e,f){return{type:z.da(e),name:"a"+f}}):1<=c?E(a.length).map(function(e){return{type:a.parameters,name:"a"+e}}):[]}function lb(a,b){if(!M(a)){var c=S(a);b.add("structs",c,function(){return"struct "+c+" { "+kb(a).map(function(e){return lb(e.type,b)||S(e.type)+" "+e.name+";"}).join("")+"};"})}}
function mb(a,b,c){if(!M(a)){var e=a.length,f=a.parameters.length;c.add("functions","mult"+e+"_"+f,function(){return S(z.da(e))+" mult"+e+"_"+f+"("+S(a)+" a, "+S(z.da(f))+" b){return "+nb(e)(E(e).map(function(g){return ob(f)(["a.a"+g,"b"],b,c)}),b,c)+";}"})}}
function pb(a,b,c){if(!(M(a)&&1>=C(a))){var e=a.length,f="sum"+S(a);c.add("functions",f,function(){return S(a.parameters)+" "+f+"("+S(a)+" a){"+(S(a.parameters)+" res = "+qb(a.parameters,0)([],b,c)+";\n      "+E(e).map(function(g){return"res = "+rb(a.parameters)(["res",R(a,g)(["a",g],b,c)],b,c)+";"}).join("\n")+"\n        return res;\n    }")})}}
function sb(a,b,c){var e=a.length,f=a.parameters.length;c.add("functions","multc"+e+"_"+f,function(){return S(z.fa(e))+" multc"+e+"_"+f+"("+S(a)+" a, "+S(z.fa(f))+" b){\n        return cvec"+e+"("+E(e).map(function(g){return tb(f)(["a.a"+g,"b"],b,c)})+");\n    }\n    "})}function ub(a,b){2<=a&&4>=a||b.add("functions","dot"+a,function(){return"float dot"+a+"(vec"+a+" a, vec"+a+" b) {\n    return "+Ua(a).map(function(c,e){return"dot(a.a"+e+",b.a"+e+")"}).join("+")+"; }\n    "})}
function vb(a,b){b.add("functions","cdot"+a,function(){return"vec2 cdot"+a+"(cvec"+a+" a, cvec"+a+" b) {\n      return "+E(a).map(function(c){return"vec2(dot(a.a"+c+",vec2(b.a"+c+".x,-b.a"+c+".y)), dot(a.a"+c+",b.a"+c+".yx))"}).join("+\n")+";\n    }\n    "})}
function wb(a,b,c){var e="add"+S(a);c.add("functions",e,function(){return S(a)+" "+e+"("+S(a)+" a, "+S(a)+" b) {\n    return "+S(a)+"("+kb(a).map(function(f){return S(f.type)+"("+rb(f.type)(["a."+f.name,"b."+f.name],b,c)+")"}).join(",")+");\n      }"})}
function xb(a,b,c){var e="sub"+S(a);c.add("functions",e,function(){return S(a)+" "+e+"("+S(a)+" a, "+S(a)+" b) {\n    return "+S(a)+"("+kb(a).map(function(f){return S(f.type)+"("+yb(f.type)(["a."+f.name,"b."+f.name],b,c)+")"}).join(",")+");\n    }"})}function zb(a,b,c){var e="scalarmult"+S(a);c.add("functions",e,function(){return S(a)+" "+e+"(float a, "+S(a)+" b) {\n    return "+S(a)+"("+kb(a).map(function(f){return S(f.type)+"("+Ab(f.type)(["a","b."+f.name],b,c)+")"}).join(",")+");\n    }"})}
function Bb(a,b,c){jb("multc",b,c);var e="cscalarmult"+S(a);c.add("functions",e,function(){return S(a)+" "+e+"(vec2 a, "+S(a)+" b) {\n    return "+S(a)+"("+kb(a).map(function(f){return""+Cb(f.type)(["a","b."+f.name],b,c)}).join(",")+");\n    }"})}
function Db(a){if(a===z.i)return P("multc");if(M(a))return function(c){return U("*")([c[1],c[0]])};var b=Ta(a);if(F(b,z.h))return function(c,e,f){return mb(a,e,f)||"mult"+a.length+"_"+a.parameters.length+"("+c.join(",")+")"};if(b===z.i)return function(c,e,f){return sb(a,e,f)||"multc"+a.length+"_"+a.parameters.length+"("+c.join(",")+")"}}function ob(a){return function(b,c,e){return ub(a,e)||"dot"+(2<=a&&4>=a?"":a)+"("+b.join(",")+")"}}
function tb(a){return function(b,c,e){return vb(a,e)||"cdot"+a+"("+b.join(",")+")"}}function rb(a){return M(a)?U("+"):function(b,c,e){return wb(a,c,e)||"add"+S(a)+"("+b.join(",")+")"}}function yb(a){return M(a)?U("-"):function(b,c,e){return xb(a,c,e)||"sub"+S(a)+"("+b.join(",")+")"}}function Eb(a){return H(a)&&1==C(a)?function(b,c,e){return ob(a.length)([b[0],nb(a.length)(Array(a.length).fill("1."),c,e)],c,e)}:function(b,c,e){return pb(a,c,e)||"sum"+S(a)+"("+b.join(",")+")"}}
function nb(a){if(2<=a&&4>=a)return function(c){return"vec"+a+"("+c.join(",")+")"};if(1==a)return function(c){return"float("+c.join(",")+")"};var b=0;return function(c,e,f){return lb(z.da(a),f)||"vec"+a+"("+Ua(a).map(function(g){return"vec"+g+"("+E(g).map(function(){return++b&&c[b-1]}).join(",")+")"}).join(",")+")"}}function hb(a){var b=C(a);return M(a)?function(c){return S(a)+"("+c.join(",")+")"}:1==b&&a.parameters===z.h?nb(a.length):function(c,e,f){return lb(a,f)||S(a)+"("+c.join(",")+")"}}
function R(a,b){var c=Ta(a);return 1==C(a)&&c===z.h?Fb(a.length,b):M(a)?function(e){return"("+e[0]+")["+b+"]"}:function(e){return"("+e[0]+").a"+b}}function qb(a,b){return M(a)?function(){return S(a)+"(float("+b+"))"}:function(c,e,f){return hb(a)+"("+kb(a).map(function(g){return qb(g.type,b)(c,e,f)}).join(",")+")"}}
function Fb(a,b){return function(c){if(1==a)return c[0];if(2<=a&&4>=a)return"("+c[0]+")["+b+"]";a:{var e=b;var f=Ua(a),g;for(g in f)if(f[g]<=e)e-=f[g];else{e={first:g,second:e};break a}console.error("Accessing index out of range");e=void 0}return"("+c[0]+").a"+e.first+"["+e.second+"]"}}function Ab(a){return M(a)?U("*"):function(b,c,e){return zb(a,c,e)||"scalarmult"+S(a)+"("+b.join(",")+")"}}
function Cb(a){return a===z.i?P("multc"):function(b,c,e){return Bb(a,c,e)||"cscalarmult"+S(a)+"("+b.join(",")+")"}}function Gb(a,b,c){var e="reverse"+S(a);c.add("functions",e,function(){return S(a)+" "+e+"("+S(a)+" a){"+(S(a.parameters)+" m;\n")+E(Math.floor(a.length/2)).map(function(f){var g=R(a,f)(["a",f],b,c);f=R(a,a.length-1-f)(["a",a.length-1-f],b,c);return"m = "+g+"; "+g+" = "+f+"; "+f+" = m;"}).join("\n")+"return a;\n      }"})}
function Hb(a){return function(b,c,e){return Gb(a,c,e)||"reverse"+S(a)+"("+b.join(",")+")"}}function Ib(a,b,c){var e="max"+S(a);c.add("functions",e,function(){return S(a.parameters)+" "+e+"("+S(a)+" a){"+(S(a.parameters)+" m = "+R(a,a.length-1)(["a",a.length-1],b,c)+";\n")+E(a.length-1).map(function(f){return"m = max(m,"+R(a,f)(["a",f],b,c)+");"}).join("\n")+"return m;\n      }"})}function Jb(a){return function(b,c,e){return Ib(a,c,e)||"max"+S(a)+"("+b.join(",")+")"}}
function Kb(a,b,c){var e="min"+S(a);c.add("functions",e,function(){return S(a.parameters)+" "+e+"("+S(a)+" a){"+(S(a.parameters)+" m = "+R(a,a.length-1)(["a",a.length-1],b,c)+";\n")+E(a.length-1).map(function(f){return"m = min(m,"+R(a,f)(["a",f],b,c)+");"}).join("\n")+"return m;\n      }"})}function Lb(a){return function(b,c,e){return Kb(a,c,e)||"min"+S(a)+"("+b.join(",")+")"}}
function Mb(a,b,c){var e="transpose"+S(a),f=G(a.parameters.length,G(a.length,a.parameters.parameters));c.add("functions",e,function(){return S(f)+" "+e+"("+S(a)+" a){return "+hb(f)(E(f.length).map(function(g){return hb(f.parameters)(E(f.parameters.length).map(function(k){return R(a.parameters,g)([R(a,k)(["a",k],b,c),g],b,c)}),b,c)}),b,c)+";}"})}function Nb(a){return function(b,c,e){return Mb(a,c,e)||"transpose"+S(a)+"("+b.join(",")+")"}};function Ob(a){function b(f,g,k){if(1<g){var l=g/2|0;b(f,l,!k);b(f+l,g-l,k);c(f,g,k)}}function c(f,g,k){if(1<g){var l;for(l=1;l<g;)l<<=1;l>>=1;for(var m=f;m<f+g-l;m++){var q=m,n=m+l;k?e.push([q,n]):e.push([n,q])}c(f,l,k);c(f+l,g-l,k)}}var e=[];b(0,a,!0);return e}
function Pb(a,b,c){var e="sort"+S(a);c.add("functions",e,function(){return S(a)+" "+e+"("+S(a)+" a){"+(S(a.parameters)+" m;\n")+Ob(a.length).map(function(f){var g=R(a,f[0])(["a",f[0]],b,c);f=R(a,f[1])(["a",f[1]],b,c);return"m = min("+g+","+f+"); "+f+" = max("+g+","+f+"); "+g+" = m;"}).join("\n")+"return a;\n      }"})}function Qb(a){return function(b,c,e){return Pb(a,c,e)||"sort"+S(a)+"("+b.join(",")+")"}};function O(a){return function(b){return va(a)+"("+b+")"}}function U(a){return function(b){return"("+b.join(a)+")"}}function V(){return function(a){return"("+a.reverse().join("*")+")"}}function Q(a){return a}var W={};W.join=N([[[z.B,z.B],z.line,O("cross")]]);W.meet=N([[[z.line,z.line],z.B,O("cross")]]);W.gauss=N([[[z.i],z.H,Q]]);W.complex=N([[[z.H],z.i,Q],[[z.B],z.i,P("dehomogenize")]]);
W["if"]=function(a){if(!a.every(function(c){return c}))return!1;if(2===a.length)return{s:a,u:a[1],m:function(c){return"if("+c[0]+") {"+c[1]+";}"}};if(3===a.length){var b=A(a[1],a[2]);return b?{s:[z.C,b,b],u:b,m:function(c){return"("+c[0]+" ? "+c[1]+" : "+c[2]+")"}}:{s:a,u:z.V,m:function(c){return"if("+c[0]+") {"+c[1]+";} else {"+c[2]+";}"}}}return!1};W["="]=function(a){a=A(a[0],a[1]);return{s:a,u:a,m:function(b){return b[0]+" = "+b[1]+";"}}};
W[";"]=function(a){return{s:a,u:a[1]!==z.V?a[1]:a[0],m:function(b){return b[0]+" ; "+b[1]+";"}}};W.repeat=function(a){return 2!=a.length&&3!=a.length||!bb(a[0])?!1:{s:a,u:a[a.length-1],m:function(){return""}}};W.forall=function(a){return 2!=a.length&&3!=a.length||"list"!==J(a[0]).type?!1:{s:a,u:a[a.length-1],m:function(){return""}}};W.apply=function(a){return 2!=a.length&&3!=a.length||"list"!==J(a[0]).type?!1:{s:a,u:G(J(a[0]).length,a[a.length-1]),m:function(){return""}}};
W.sum=function(a){return 1==a.length&&(H(a[0])||I(a[0]))?{s:a,u:a[0].parameters,m:Eb(a[0])}:!1};W.regional=function(a){return{s:a,u:z.V,m:function(){return""}}};W.sqrt=N([[[z.h],z.i,P("sqrtf")],[[z.i],z.i,P("sqrtc")]]);W.abs=N([[[z.h],z.h,O("abs")],[[z.i],z.h,O("length")],[[z.H],z.h,O("length")],[[z.L],z.h,O("length")],[[z.R],z.h,O("length")]]);W.abs_infix=W.abs;
W.dist=N([[[z.h,z.h],z.h,function(a){return O("abs")(U("-")(a))}],[[z.i,z.i],z.h,function(a){return O("length")(U("-")(a))}],[[z.H,z.H],z.h,function(a){return O("length")(U("-")(a))}],[[z.L,z.L],z.h,function(a){return O("length")(U("-")(a))}],[[z.R,z.R],z.h,function(a){return O("length")(U("-")(a))}]]);W.dist_infix=W.dist;W.sin=N([[[z.h],z.h,O("sin")],[[z.i],z.i,P("sinc")]]);W.cos=N([[[z.h],z.h,O("cos")],[[z.i],z.i,P("cosc")]]);W.tan=N([[[z.h],z.h,O("tan")],[[z.i],z.i,P("tanc")]]);
W.exp=N([[[z.h],z.h,O("exp")],[[z.i],z.i,P("expc")]]);W.arctan=N([[[z.h],z.h,O("atan")],[[z.i],z.i,P("arctanc")]]);W.arcsin=N([[[z.h],z.i,P("arcsinf")],[[z.i],z.i,P("arcsinc")]]);W.arccos=N([[[z.h],z.i,P("arccosf")],[[z.i],z.i,P("arccosc")]]);W.log=N([[[z.h],z.i,P("logr")],[[z.i],z.i,P("logc")]]);var Rb=[2,3,4].map(function(a){return G(a,z.h)}).concat([2,3,4].map(function(a){return G(a,G(a,z.h))})),Sb=[z.v,z.h,z.i].concat(Rb);
W.add=function(a){var b=N(Sb.map(function(c){return[[c,c],c,U("+")]}).concat([[[z.B,z.B],z.H,P("addpoints")]]))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(c){return H(c)||I(c)})&&cb(b,a))return a=A(L(b),L(a)),{s:[a,a],u:a,m:rb(a)}};
W.sub=function(a){var b=N(Sb.map(function(c){return[[c,c],c,U("-")]}).concat(Sb.map(function(c){return[[z.V,c],c,U("-")]})).concat([[[z.B,z.B],z.H,P("subpoints")]]))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(c){return H(c)||I(c)})&&cb(b,a))return a=A(L(b),L(a)),{s:[a,a],u:a,m:yb(a)}};W["+"]=W.add;W["-"]=W.sub;
W._=function(a){var b=J(a[0]);if(b===z.B||b===z.line)b=z.L;if("list"===b.type&&bb(a[1])){var c=Number(a[1].value.value.real);return 1<=Math.abs(c)&&Math.abs(c)<=b.length?(0<c&&--c,0>c&&(c=b.length+c),{s:a,u:b.parameters,m:R(b,c)}):{s:a,u:b.parameters,m:function(){return console.error("try to access "+c+"-th Element of "+b.length+"-list "+JSON.stringify(a[0]))}}}return!1};
W.mult=function(a){var b=N([[[z.v,z.v],z.v,U("*")],[[z.h,z.h],z.h,U("*")],[[z.i,z.h],z.i,U("*")],[[z.h,z.i],z.i,U("*")],[[z.i,z.i],z.i,P("multc")],[[z.aa,z.aa],z.aa,V()],[[z.ba,z.ba],z.ba,V()],[[z.ca,z.ca],z.ca,V()],[[z.aa,z.H],z.H,V()],[[z.ba,z.L],z.L,V()],[[z.ca,z.R],z.R,V()],[[z.H,z.aa],z.H,V()],[[z.L,z.ba],z.L,V()],[[z.R,z.ca],z.R,V()]])(a);if(b)return b;if(2!==a.length)return!1;b=a[0];var c=a[1];if([b,c].every(function(e){return"list"===e.type&&F(e.parameters,z.h)})&&b.length===c.length)return a=
L(b),M(a)?{s:[a,a],u:z.h,m:O("dot")}:{s:[a,a],u:z.h,m:ob(b.length)};if([b,c].every(function(e){return"list"===e.type&&F(e.parameters,z.i)})&&b.length===c.length)return a=db(b),{s:[a,a],u:z.i,m:tb(b.length)};if(H(b)&&2===C(b)&&H(c)&&1===C(c)&&b.parameters.length===c.length)return{s:[L(b),L(c)],u:z.da(b.length),m:Db(L(b))};if(I(b)&&2===C(b)&&I(c)&&1===C(c)&&b.parameters.length===c.length)return{s:[db(b),db(c)],u:z.fa(b.length),m:Db(db(b))};for(b={J:0};2>b.J;b={X:b.X,J:b.J,Y:b.Y},b.J++){if(F(a[0^b.J],
z.h)&&(H(a[1^b.J])||I(a[1^b.J])))return b.X=L(a[1^b.J]),{s:b.J?[b.X,z.h]:[z.h,b.X],u:b.X,m:function(e){return function(f,g,k){return Ab(e.X)([f[0^e.J],f[1^e.J]],g,k)}}(b)};if(F(a[0^b.J],z.i)&&I(a[1^b.J]))return b.Y=db(a[1^b.J]),{s:b.J?[b.Y,z.i]:[z.i,b.Y],u:b.Y,m:function(e){return function(f,g,k){return Cb(e.Y)([f[0^e.J],f[1^e.J]],g,k)}}(b)}}};W["*"]=W.mult;
W.div=function(a){var b=N([[[z.h,z.h],z.h,U("/")],[[z.h,z.i],z.i,P("divfc")],[[z.i,z.h],z.i,U("/")],[[z.i,z.i],z.i,P("divc")]])(a);return b?b:F(a[1],z.h)&&I(a[0])&&(a=L(a[0]),M(a))?{s:[a,z.h],u:a,m:U("/")}:!1};W["/"]=W.div;W.re=N([[[z.i],z.h,P("realc")]]);W.im=N([[[z.i],z.h,P("imagc")]]);W.floor=N([[[z.h],z.v,function(a){return"int(floor("+a+"))"}],[[z.i],z.i,O("floor")]]);W.round=N([[[z.h],z.v,function(a){return"int(floor("+a+"+.5))"}],[[z.i],z.i,function(a){return"floor("+a+"+vec2(.5))"}]]);
W.ceil=N([[[z.h],z.v,function(a){return"int(ceil("+a+"))"}],[[z.i],z.i,O("ceil")]]);W.mod=N([[[z.v,z.v],z.v,function(a,b){return"int("+O("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[[z.h,z.h],z.h,O("mod")],[[z.i,z.i],z.i,P("mod")]]);W.random=N([[[],z.h,P("random")],[[z.h],z.h,function(a,b,c){return P("random")([],b,c)+"*"+a[0]}],[[z.i],z.i,function(a,b,c){return"vec2("+P("random")([],b,c)+","+P("random")([],b,c)+")*"+a[0]}]]);
W.randomint=N([[[z.v],z.v,function(a,b,c){return"int(floor("+P("random")([],b,c)+"*float("+a[0]+")))"}],[[z.h],z.v,function(a,b,c){return"int(floor("+P("random")([],b,c)+"*floor("+a[0]+")))"}]]);W.randominteger=W.randomint;W.randombool=N([[[],z.C,function(a,b,c){return"("+P("random")([],b,c)+">.5)"}]]);W.randomnormal=N([[[],z.h,P("randomnormal")]]);
W.arctan2=N([[[z.h,z.h],z.h,function(a){return"atan("+a[1]+", "+a[0]+")"}],[[z.i,z.i],z.i,P("arctan2c")],[[z.i],z.h,P("arctan2vec2")],[[z.H],z.h,P("arctan2vec2")],[[z.fa(2)],z.i,P("arctan2cvec2")]]);["red","green","blue","gray","hue"].forEach(function(a){W[a]=N([[[z.h],z.L,P(a)]])});W.grey=W.gray;W.min=function(a){var b=N([[[z.h,z.h],z.h,O("min")]])(a);if(b)return b;if(1===a.length&&1===C(a[0])&&H(a[0]))return{s:a,u:a[0].parameters,m:Lb(a[0])}};
W.max=function(a){var b=N([[[z.v,z.v],z.v,O("max")],[[z.h,z.h],z.h,O("max")]])(a);if(b)return b;if(1===a.length&&1===C(a[0])&&H(a[0]))return{s:a,u:a[0].parameters,m:Jb(a[0])}};function Tb(a,b){if(!(1>=a))if(2==a)b.add("functions","raise2",function(){return"float raise2(float a) { return a*a; }"});else{Tb(2,b);var c=function(f,g){return 1==g?f:g&1?c(f,g-1)+"*a":"raise2("+c(f,g/2)+")"},e="raise"+a;b.add("functions",e,function(){return"float "+e+"(float a) { return "+c("a",a)+";}"})}}
function Ub(a){return function(b,c,e){return 0==a?"1.":1==a?b[0]:Tb(a,e)||"raise"+a+"("+b[0]+")"}}W.pow=function(a){if(bb(a[1])&&F(a[0],z.h)){var b=Number(a[1].value.value.real);if(0<=b)return{s:[z.h,a[1]],u:z.h,m:Ub(b)}}return N([[[z.h,z.v],z.h,P("powi")],[[z.i,z.i],z.i,P("powc")]])(a)};W["^"]=W.pow;W.re=N([[[z.i],z.h,function(a){return"("+a+").x"}]]);W.conjugate=N([[[z.i],z.i,P("conjugate")]]);W.im=N([[[z.i],z.h,function(a){return"("+a+").y"}]]);
W.genList=function(a){var b=a.length;if(0<b){var c=!1,e;for(e in a)c=A(c,a[e]);if(c)return a=G(b,c),{s:Array(b).fill(c),u:a,m:hb(a)}}return!1};W["&"]=N([[[z.C,z.C],z.C,U("&&")]]);W["%"]=N([[[z.C,z.C],z.C,U("||")]]);"> < >= <= == !=".split(" ").forEach(function(a){W[a]=N([[[z.v,z.v],z.C,U(a)],[[z.h,z.h],z.C,U(a)]])});W["!"]=N([[[z.C],z.C,O("!")],[[z.V,z.C],z.C,function(a){return O("!")([a[1]])}]]);W.not=W["!"];W.imagergb=N([[[z.image,z.M],z.L,Vb],[[z.M,z.M,z.image,z.M],z.L,Wb]]);
W.imagergba=N([[[z.image,z.M],z.R,Xb],[[z.M,z.M,z.image,z.M],z.R,Yb]]);W.reverse=function(a){return 1===a.length&&"list"===a[0].type?{s:a,u:a[0],m:Hb(a[0])}:!1};W.sort=function(a){return 1===a.length&&1===C(a[0])&&H(a[0])?{s:a,u:a[0],m:Qb(a[0])}:!1};W.transpose=function(a){return 1===a.length&&2<=C(a[0])?{s:a,u:G(a[0].parameters.length,G(a[0].length,a[0].parameters.parameters)),m:Nb(a[0])}:!1};W.det=N([[[z.aa],z.h,P("det2")],[[z.ba],z.h,P("det3")],[[z.ca],z.h,P("det4")],[[z.B,z.B,z.B],z.h,P("det3v")]]);
Object.freeze(W);T.powc=["expc","multc","logc"];T.sqrtc=["expc","multc","logc"];T.arccosc=["multc","negc","sqrtc","addc","logc"];T.arcsinc=["multc","negc","sqrtc","addc","logc"];T.tanc=["sinc","cosc","divc"];T.arctanc=["logc","addc","multc","subc"];T.arctan2c=["logc","divc","sqrtc","multc"];T.arctan2vec2c=["arctan2c"];T.hue=["hsv2rgb"];T.randomnormal=["random"];T.subpoints=["dehomogenize"];T.addpoints=["dehomogenize"];Object.freeze(T);function Qa(a){this.j={};this.G={};this.l={};this.T=0;this.D={};this.F=a;this.P={}}Qa.prototype.add=function(a,b,c){this.mark(a,b);this.l[a].ka[b]||(this.l[a].ka[b]=c(),this.l[a].ia[b]=!0,this.l[a].order.push(b))};Qa.prototype.mark=function(a,b){this.l[a]||(this.l[a]={order:[],ia:{},ka:{}});var c=this.l[a].ia[b]||!1;this.l[a].ia[b]=!0;return c};function Zb(a,b){return a.l[b]?a.l[b].order.map(function(c){return a.l[b].ka[c]}).join("\n"):"\n"}
function X(a,b,c,e){if(fb(c,e))return b;if(F(c,e)){if("constant"===c.type)return ib(c.value,e);var f=gb(e)([c]);if(!f)return console.error("cannot find an implementation for "+B(c)+" -> "+B(e)+", using identity"),b;e=f.m;return e(X(a,b,c,f.s[0]),{},a)}console.error(B(c)+" is no subtype of "+B(e)+" (trying to cast the term "+b+")");return b}function Y(a,b,c){a.j[b]||(a.j[b]={});a.j[b].U||(a.j[b].U=[]);a.j[b].A||(a.j[b].A=!1);a.hasOwnProperty("global")||(a.j[b].global=c)}
function $b(a,b){var c=b.K;if(b.isuniform)return a.G[b.uvariable].type;if("variable"===b.ctype)return b=b.name,b=c[b]||b,a.j[b].A;if("function"===b.ctype&&a.D.hasOwnProperty(b.oper))return a.j[c[b.oper]].A;if("number"===b.ctype)return Va(b);if("void"===b.ctype)return z.V;if("field"===b.ctype){a=J(Z(a,b.obj));if(1==b.key.length){if("list"===a.type)return a.parameters;if(F(a,z.B))return z.h}else if("xy"==b.key&&F(a,z.B))return z.H;if(!a)return!1}else{if("string"===b.ctype)return z.image;if("function"===
b.ctype||"infix"===b.ctype){c=Array(b.args.length);for(var e=!0,f=0;f<b.args.length;f++)c[f]=Z(a,b.args[f]),e&="constant"===c[f].type;if(e&&b.impl)return b={ctype:b.ctype,oper:b.oper,impl:b.impl,args:c.map(function(g){return g.value})},b=a.F.evaluateAndVal(b),Va(b);a=va(b.oper);e=W[a]?W[a](c):!1;if(!e&&c.every(function(g){return Ta(g)}))throw console.error("Could not find an implementation for "+a+" with args ("+c.map(B).join(", ")+")"),console.log(b),"error";return e?e.u:!1}}console.error("Don't know how to compute type of");
console.log(b);return!1}function Z(a,b){if(!b.pa||!b.T||a.T>b.T)b.pa=$b(a,b),b.T=a.T;return b.pa}
function ac(a,b,c){function e(m,q,n){var t={},u;for(u in m)t[u]=m[u];m=ya();Y(l,m,!1);g[m].A=n;g[m].qa=!0;t[q]=m;return t}function f(m,q,n,t){m.K=q;for(var u in m.args){var D=t||"repeat$2"===m.oper&&0==u||"repeat$3"===m.oper&&0==u||"_"===m.oper&&1==u,K=q;-1!==["repeat","forall","apply"].indexOf(va(m.oper))&&(1==u?K="repeat$2"===m.oper?e(q,"#",z.v):"repeat$3"===m.oper?e(q,m.args[1].name,z.v):"forall$2"===m.oper||"apply$2"===m.oper?e(q,"#",!1):"forall$3"===m.oper||"apply$3"===m.oper?e(q,m.args[1].name,
!1):q:2==u&&(K=m.args[1].K));f(m.args[u],K,n,D)}"field"===m.ctype&&f(m.obj,q,n,t);"variable"===m.ctype&&(u=m.name,u=q[u]||u,t&&l.j[u]&&(l.j[u].Z=!0));if("="===m.oper)t=m.args[0].name,t=q[t]||t,Y(l,t,!0),g[t].U.push(m.args[1]);else if(m.oper&&"regional"===va(m.oper)&&"global"!=n)for(var sa in m.args){t=m.args[sa].name;var ta=ya();q[t]=ta;k[n].j||(k[n].j=[]);k[n].j.push(ta);Y(l,ta,!1)}else if("forall$2"===m.oper||"apply$2"===m.oper||"forall$3"===m.oper||"apply$3"===m.oper)g[2===m.args.length?m.args[1].K["#"]:
m.args[2].K[m.args[1].name]].U.push({ctype:"infix",oper:"_",args:[m.args[0],{ctype:"number",value:{real:1,imag:0}}],K:m.args[0].K});else if("function"===m.ctype&&k.hasOwnProperty(m.oper)){n=m.oper;sa=n.replace("$","_");Y(l,sa,!1);q[n]=sa;q={};for(ta in k[n].arglist)u=k[n].arglist[ta].name,D=sa+"_"+u,q[u]=D,Y(l,D,!1),g[D].U.push(m.args[ta]);k[n].sa||(k[n].sa=!0,f(k[n].body,q,n,t),g[sa].U.push(k[n].body))}}var g=a.j,k=a.D,l=a;f(b,c,"global",!1)}
function bc(a,b){function c(n){if(n.hasOwnProperty("dependsOnPixel"))return n.dependsOnPixel;if("variable"===n.ctype){var t=n.name;t=n.K[t]||t;return k[t]?n.dependsOnPixel=!0:n.dependsOnPixel=!1}t="random randomint randominteger randombool randomnormal verbatimglsl".split(" ");if("function"===n.ctype&&-1!==t.indexOf(va(n.oper)))return n.dependsOnPixel=!0;if("repeat$2"===n.oper||"forall$2"===n.oper||"apply$2"===n.oper)return c(n.args[1])?(k[n.args[1].K["#"]]=!0,n.dependsOnPixel=!0):n.dependsOnPixel=
!1;if("repeat$3"===n.oper||"forall$3"===n.oper||"apply$3"===n.oper)return c(n.args[2])?(k[n.args[2].K[n.args[1].name]]=!0,n.args[1].dependsOnPixel=!0,n.dependsOnPixel=!0):n.dependsOnPixel=!1;for(var u in n.args)if(c(n.args[u]))return n.dependsOnPixel=!0;return"function"===n.ctype&&g.hasOwnProperty(n.oper)&&c(g[n.oper].body)?n.dependsOnPixel=!0:"field"===n.ctype?n.dependsOnPixel=c(n.obj):n.dependsOnPixel=!1}function e(n,t){if(c(n)){for(var u in n.args)e(n.args[u],t||"repeat$2"===n.oper&&0==u||"repeat$3"===
n.oper&&0==u||"_"===n.oper&&1==u);"field"===n.ctype&&e(n.obj,t);"function"===n.ctype&&g.hasOwnProperty(n.oper)&&(n=n.oper,m.hasOwnProperty(n)||(m[n]=!0,e(g[n].body,t)))}else if("boolean"!==n.ctype&&"number"!==n.ctype&&"void"!==n.ctype){".."===n.oper&&(t=!0);u=!1;var D;for(D in q)if(!u&&ua(n,q[D].W)){u=!0;var K=D}u||(K=ya(),q[K]={W:n,type:!1,Z:t});q[K].Z=q[K].Z||t;n.isuniform=!0;n.uvariable=K}}var f=a.j,g=a.D,k={cgl_pixel:!0,"cgl_pixel.x":!0,"cgl_pixel.y":!0},l;for(l in f)if(1<=f[l].U.length||f[l].qa)k[l]=
!0;c(b);var m={"":!0},q=a.G;e(b,!1)}function cc(a,b){if("function"===b.ctype&&!a.D.hasOwnProperty(b.oper)&&null!==a.F.getMyfunction(b.oper)){var c=b.oper;a.D[c]=ra(a.F.getMyfunction(c));cc(a,a.D[c].body)}for(var e in b.args)cc(a,b.args[e])}
function dc(a,b){function c(l){var m={},q;for(q in l)m[q]=l[q];return m}function e(l,m){"repeat$2"===l.oper||"forall$2"===l.oper||"apply$2"===l.oper?(m=c(m),m["#"]=!0):"repeat$3"===l.oper||"forall$3"===l.oper||"apply$3"===l.oper?(m=c(m),m[l.args[1].name]=!0):"="===l.oper&&(m[l.args[0].name]=!0);for(var q in l.args)e(l.args[q],m);"field"===l.ctype&&e(l.obj,m);"variable"===l.ctype&&(l=l.name,m[l]||(g[l]=!0))}var f={},g={};e(b,{});Y(a,"cgl_pixel",!1);a.j.cgl_pixel.A=z.H;if(1==Object.keys(g).length)f[Object.keys(g)[0]]=
"cgl_pixel";else if(g["#"])f["#"]="cgl_pixel";else if(g.x&&g.y)Y(a,"cgl_pixel.x",!1),a.j["cgl_pixel.x"].A=z.h,f.x="cgl_pixel.x",Y(a,"cgl_pixel.y",!1),a.j["cgl_pixel.y"].A=z.h,f.y="cgl_pixel.y";else{b=[];for(var k in g)a.F.nada==a.F.evaluateAndVal({ctype:"variable",name:k})&&b.push(k);1==b.length?f[b[0]]="cgl_pixel":g.p?f.p="cgl_pixel":g.z&&(f.z="cgl_pixel")}"cgl_pixel"===f.z&&(a.j.cgl_pixel.A=z.i);return f}
Qa.prototype.compile=function(a,b){var c=this,e=Z(this,a);if(a.isuniform)return a=a.uvariable,b?{code:"",o:"constant"===e.type?ib(e.value,J(e)):a}:{code:""};if(";"===a.oper){e={o:""};for(var f="",g=a.args.length-1,k=g;0<=k;k--)"void"===a.args[k].ctype&&(g=k-1);for(k=0;k<=g;k++)e=this.compile(a.args[k],b&&k===g),f+=e.code;return b?{code:f,o:e.o}:{code:f}}if("constant"===e.type)return b?{o:ib(e.value,J(e)),code:""}:{code:""};if("="===a.oper)return e=this.compile(a.args[1],!0),a=this.compile(a.args[0],
!0).o+" = "+X(this,e.o,Z(this,a.args[1]),Z(this,a.args[0])),b?{code:e.code,o:a}:{code:e.code+a+";\n"};if("repeat$2"===a.oper||"repeat$3"===a.oper){f=this.compile(a.args[0],!0);if("constant"!==Z(this,a.args[0]).type)return console.error("repeat possible only for fixed constant number in GLSL"),!1;e="repeat$2"===a.oper?a.args[1].K["#"]:a.args[2].K[a.args[1].name];f=Number(f.o);g="";if("constant"===this.j[e].A.type)for(k=1;k<=f;k++){this.j[e].A=ab(k);this.T++;var l=this.compile(a.args["repeat$2"===a.oper?
1:2],k===f&&b);g+=l.code;if(k===f&&b)return{code:g,o:l.o}}else if(k="",l=this.compile(a.args["repeat$2"===a.oper?1:2],b),a=Z(this,a.args["repeat$2"===a.oper?1:2]),b&&(k=ya(),this.j[k]||(Y(this,k,!0),this.j[k].A=a)),g=g+("for(int "+e+"=1; "+e+" <= "+f+"; "+e+"++) {\n")+l.code,b&&(g+=k+" = "+l.o+";\n"),g+="}\n",b)return{code:g,o:k};return{code:g}}if("forall$2"===a.oper||"forall$3"===a.oper||"apply$2"===a.oper||"apply$3"===a.oper){var m=Z(this,a.args[0]);if("list"!==m.type&&("constant"!==m.type||"list"!==
m.value.ctype))return console.error(a.oper+" only possible for lists"),!1;f=m.length||m.value.value.length;k=2===a.args.length?a.args[1].K["#"]:a.args[2].K[a.args[1].name];var q=this.j[k].A,n=l="";b&&(n=ya(),l+=S(e)+" "+n+";\n");"list"===e.type&&lb(e,this);if("constant"===this.j[k].A.type||"constant"===m.type)for(m=this.F.evaluateAndVal(a.args[0]),q=0;q<f;q++)this.j[k].A=Va(m.value[q]),this.T++,g=this.compile(a.args[2===a.args.length?1:2],b),l+=g.code,"forall$2"===a.oper||"forall$3"===a.oper?q+1===
f&&b&&(l+=n+" = "+g.o+";\n"):b&&(l+=R(e,q)([n],[],this)+" = "+g.o+";\n");else{g=this.compile(a.args[2===a.args.length?1:2],b);var t=this.compile(a.args[0],!0);l+=t.code;var u=t.o;!this.j[u]&&!this.G[u]&&2<=m.length&&(u=ya(),l+=S(m)+" "+u+" = "+t.o+";\n");this.j[k].global=!0;for(t=0;t<f;t++)l+=k+" = "+R(m,t)([u],[],this)+";\n",l+=g.code,b&&("forall$2"===a.oper||"forall$3"===a.oper?t===f-1&&(l+=n+" = "+g.o+";\n"):l+=R(e,t)([n],[],this)+" = "+g.o+";\n");"list"===q.type&&lb(q,this)}return b?{code:l,o:n}:
{code:l}}if("if$2"===a.oper||"if$3"===a.oper){l=this.compile(a.args[0],!0);f=Z(this,a.args[0]);k=g="";n=this.compile(a.args[1],b);b&&(k=ya(),this.j[k]||(Y(this,k,!0),this.j[k].A=e));"constant"!=f.type&&(g+=l.code,g+="if("+l.o+") {\n");if("constant"!=f.type||"constant"==f.type&&f.value.value)g+=n.code,b&&(g+=k+" = "+X(this,n.o,Z(this,a.args[1]),e)+";\n");"if$3"===a.oper&&(l=this.compile(a.args[2],b),"constant"!=f.type&&(g+="} else {\n"),"constant"!=f.type||"constant"==f.type&&!f.value.value)&&(g+=
l.code,b&&(g+=k+" = "+X(this,l.o,Z(this,a.args[2]),e)+";\n"));"constant"!=f.type&&(g+="}\n");return b?{code:g,o:k}:{code:g}}if("function"===a.ctype||"infix"===a.ctype){l=a.oper;if("verbatimglsl"===va(l))return a=this.F.evaluateAndVal(a.args[0]).value,b?{o:a,code:""}:{code:a};e=a.args.map(function(D){return c.compile(D,!0)});f=a.args.map(function(D){return Z(c,D)});if(this.D.hasOwnProperty(l))for(k=ec(this,l),g=Array(e.length),n=0;n<e.length;n++)g[n]=this.j[this.D[l].body.K[this.D[l].arglist[n].name]].A;
else{l=va(l);if("regional"===l)return b?{o:"",code:""}:{code:""};k=W[l](f);if(!k)return console.error("Could not find an implementation for "+l+"("+f.map(B).join(", ")+").\nReturning empty code"),b?{o:"",code:""}:{code:""};g=k.s;k=k.m}l="";n=Array(e.length);for(m=0;m<e.length;m++)l+=e[m].code,n[m]=X(this,e[m].o,f[m],g[m]);a=k(n,a.modifs,this);return b?{o:a,code:l}:{code:l+a+";\n"}}if("variable"===a.ctype)return e=a.name,e=a.K[e]||e,b?{o:e,code:""}:{code:e+";\n"};if("void"===a.ctype)return b?{o:"",
code:""}:{code:""};if("field"===a.ctype&&(e=Z(this,a.obj),k={x:0,y:1,z:2,r:0,g:1,b:2,a:3}[a.key],f=!1,g=c.compile(a.obj,!0).o,void 0!=k&&"list"===e.type?f=R(e,k)([g],null,this):"xy"===a.key&&"list"===e.type?(2===e.length&&(f=g),3===e.length&&(f=P("dehomogenize")([X(c,g,e,z.B)],null,this))):e===z.B&&(k={xy:"dehomogenize",x:"dehomogenizex",y:"dehomogenizey"},k[a.key]&&(f=P(k[a.key])([X(c,g,e,z.B)],null,this))),f))return b?{o:f,code:""}:{code:f+";\n"};console.error("dont know how to this.compile "+JSON.stringify(a))};
function ec(a,b){fc(a,b,a.D[b].arglist.length);return O(b.replace("$","_"))}
function fc(a,b,c){if(!a.mark("compiledfunctions",b)){for(var e=a.D[b],f=b.replace("$","_"),g=e.body.K,k=Array(c),l=0;l<c;l++)k[l]=e.arglist[l].name;c=a.j[f].A===z.V;var m=S(a.j[f].A)+" "+f+"("+k.map(function(n){return S(a.j[g[n]].A)+" "+g[n]}).join(", ")+"){\n";for(q in e.j)k=e.j[q],m+=S(a.j[k].A)+" "+k+";\n";var q=a.compile(e.body,!c);e=Z(a,e.body);m+=q.code;c||(m+="return "+X(a,q.o,e,a.j[f].A)+";\n");m+="}\n";a.add("compiledfunctions",b,function(){return m})}}
function Pa(a,b){xa=0;var c=b=ra(b);cc(a,c);ac(a,c,dc(a,c));bc(a,c);for(var e in a.G){c=a.F.evaluateAndVal(a.G[e].W);if(!c.ctype||"undefined"===c.ctype){console.error("can not evaluate:");console.log(a.G[e].W);break}a.G[e].type=a.G[e].Z?Va(c):wa(c)}e=!0;for(var f in a.j)a.j[f].A=a.j[f].A||!1,a.j[f].Z&&(a.j[f].A=ab(1),a.T++);for(;e;){e=!1;for(var g in a.j)if(!a.j[g].Z)for(var k in a.j[g].U)c=J(Z(a,a.j[g].U[k])),f=a.j[g].A||!1,c&&(c=f?F(c,f)?f:A(f,c):c)&&c!==f&&(a.j[g].A=c,a.T++,e=!0)}for(var l in a.G)"list"===
a.G[l].type.type&&lb(a.G[l].type,a);for(var m in a.j)"list"===a.j[m].A.type&&lb(a.j[m].A,a);g=a.compile(b,!0);k=Z(a,b);b=X(a,g.o,k,z.color);F(k,z.color)||console.error("expression does not generate a color");k=Zb(a,"structs");k+=Zb(a,"uniforms");l=[];for(var q in a.G)"constant"!=a.G[q].type.type&&a.G[q].type!=z.image&&l.push("uniform "+S(a.G[q].type)+" "+q+";");k+=l.join("\n");q="";for(var n in a.P)q+=a.P[n].code+"\n";k=k+q+Zb(a,"includedfunctions");k+=Zb(a,"functions");for(var t in a.j)a.j[t].A&&
a.j[t].global&&(k+=S(a.j[t].A)+" "+t+";\n");k+=Zb(a,"compiledfunctions");k+="void main(void) {\n"+g.code+"gl_FragColor = "+b+";\n}\n";console.log(k);n={};if(a.l.compiledfunctions)for(var u in a.l.compiledfunctions.ia)n[u]=a.F.getMyfunction(u).generation;return{code:k,G:a.G,P:a.P,ga:n}};function gc(a,b,c,e){this.W=b;this.F=e;this.D=c;hc(this);b=this.l;this.name=a;this.code="uniform sampler2D _sampler"+a+";\nuniform float _ratio"+a+";\nuniform vec2 _cropfact"+a+";\nvec4 _imagergba"+a+"(vec2 A, vec2 B, vec2 p) {\n  p -= A; B -= A;\n  float b = dot(B,B);\n  p = vec2(dot(p,B),_ratio"+a+"*dot(p,vec2(-B.y,B.x)))/b;\n  "+(b.repeat?"p = mod(p, vec2(1.));":"")+"\n  "+(b.repeat&&b.mipmap?"vec4 color = vec4(0.);\n    float totalWeight = 0.;\n    for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {\n      vec2 delta = .5*vec2(dx, dy);\n      vec2 center = delta+vec2(.5);\n      vec2 tc = fract(p-delta)+delta;\n      float dst = dot(abs(tc-center),vec2(1.));\n      float w = max(.5-dst,0.);\n      w=w*w;\n      color += w * texture2D(_sampler"+
a+", tc*_cropfact"+a+");\n      totalWeight += w;\n    }\n    return color/totalWeight;":b.repeat?"return texture2D(_sampler"+a+", p*_cropfact"+a+");":"if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)\n          return texture2D(_sampler"+a+", p*_cropfact"+a+");\n       else\n          return vec4(0.);")+"\n  }"}
function hc(a){var b=a.D,c=a.F;b={interpolate:b.hasOwnProperty("interpolate")?c.evaluateAndVal(b.interpolate).value:!0,mipmap:b.hasOwnProperty("mipmap")?c.evaluateAndVal(b.mipmap).value:!1,repeat:b.hasOwnProperty("repeat")?c.evaluateAndVal(b.repeat).value:!1};!a.l||a.l.mipmap==b.mipmap&&a.l.repeat==b.repeat||(console.log("enfore recompilation because texture modifiers changed."),na++);a.l=b}
function Xa(a){var b=a.F.evaluateAndVal(a.W).value,c="string"===typeof b?a.F.getImage(b,!0):b;if(null==c)return console.error("Could not find image "+b+"."),w;hc(a);return Ja(c,a.F,a.l)}function ic(a,b,c){c.P.hasOwnProperty(a)||(c.P[a]=new gc(a,c.G[a].W,b,c.F));return a}function Yb(a,b,c){return["_imagergba",ic(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}function Wb(a,b,c){return["(_imagergba",ic(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}
function Xb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["_imagergba",ic(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],")"].join("")}function Vb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["(_imagergba",ic(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],").rgb)"].join("")};function jc(a){var b=void 0===b?null:b;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function $a(a){var b=void 0===b?[.5,.5,.5]:b;if("number"===a.ctype){var c=kc(a);if(!isNaN(c))return[c,c,c]}a=jc(a);return null===a?b:3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(e){return kc(e)})}
function Za(a){var b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function kc(a){var b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function pa(a){this.message=a}pa.prototype.toString=function(){return this.message};
function Ma(a,b){var c=v;this.handle=c.createProgram();c.l&&(a="#version 300 es\n"+a.replace(/attribute/g,"in").replace(/varying/g,"out"),b="#version 300 es\n"+b.replace(/varying/g,"in").replace(/gl_FragColor/g,"FragColor").replace(/texture2D/g,"texture").replace(/precision highp float;/g,"precision highp float;\n#define webgl2 true\nout vec4 FragColor;"));lc(this,c,c.VERTEX_SHADER,a);lc(this,c,c.FRAGMENT_SHADER,b);a=this.handle;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new pa("Error linking shader:\n"+
c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new pa("Error validating shader:\n"+c.getProgramInfoLog(a));var e=this.handle,f,g,k={},l;b=c.getProgramParameter(e,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a){var m=c.getActiveUniform(e,a);if(null!==m&&(f=m.name.replace(/\]/g,""))){for(l=k;null!==(g=/[.\[]/.exec(f));){var q=f.substr(0,g.index);l.hasOwnProperty(q)?l=l[q]:"."===g[0]?l=l[q]={}:l=l[q]=[];f=f.substr(g.index+1)}if(1<m.size){g=m.size;var n=Array(g);
for(q=0;q<g;++q){var t=m.name+"["+q+"]";t=mc(this,c,t,m);n[q]=t}l[f]=n}else t=mc(this,c,m.name,m),l[f]=t}}this.uniform=k}function lc(a,b,c,e){c=b.createShader(c);b.shaderSource(c,e);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(e.split("\n")),new pa("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.handle,c)}Ma.prototype.use=function(a){a.useProgram(this.handle);return this};
function mc(a,b,c,e){a=b.getUniformLocation(a.handle,c);switch(e.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new pa("Unknown data type for uniform "+c);}};
}).call(this);//# sourceMappingURL=CindyGL.js.map


